// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // No Prisma 7, o CLI usa esta URL para migrações. 
    // Para o Supabase, isso DEVE ser a conexão direta (porta 5432).
    url: process.env["DIRECT_URL"] || "",
  },
});
